openapi: 3.0.3
info:
  title: Goomar API
  version: 1.0.0
  description: API for creating date/time/type entries in Goomar application

paths:
  /entries:
    post:
      tags:
        - Entries
      summary: Create a new entry
      description: Creates a new record with a date, time, type, and email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - date
                - time
                - type
                - email
              properties:
                date:
                  type: string
                  format: date
                  example: "2025-09-01"
                time:
                  type: string
                  format: time
                  example: "14:30:00"
                type:
                  type: integer
                  example: 1
                email:
                  type: string
                  example: "user@example.com"
      responses:
        "201":
          description: Entry created successfully (no content returned)
