openapi: 3.0.3
info:
  title: Goomar API
  version: 1.0.0
  description: API for creating date/time/type entries in Goomar application

security:
  - bearerAuth: [ ]
servers:
  - url: http://localhost:9999
paths:
  /V1/reservation:
    post:
      tags:
        - Reservation
      summary: Post reservation from public page
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/ReservationRest'
      responses:
        '201':
          description: create/update reservation
          content:
            application/json:
              schema:
                type: integer
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only
  schemas:
    ReservationRest:
      required:
        - id
        - username
        - email
        - phone
        - registration
        - longService
      properties:
        id:
          type: integer
        username:
          type: string
          minLength: 5
          maxLength: 128
        date:
          type: string
          format: date-time
        email:
          type: string
          minLength: 5
          maxLength: 80
        phone:
          type: string
          minLength: 5
          maxLength: 80
        registration:
          type: string
          minLength: 5
          maxLength: 80
        longService:
          type: boolean
