openapi: 3.0.3
info:
  title: Goomar API
  version: 1.0.0
  description: API for creating date/time/type entries in Goomar application

security:
  - bearerAuth: [ ]
servers:
  - url: http://localhost:9999
paths:
  /google/auth:
    get:
      summary: Initiate Google OAuth2 authorization
      tags:
        - Google
      operationId: googleAuth
      description: |
        Redirects the user to the Google authorization page to grant access.
        Returns an HTML link for the user to authorize Google access.
      responses:
        '200':
          description: HTML page containing authorization link
          content:
            text/html:
              schema:
                type: string
                example: '<a href="https://accounts.google.com/o/oauth2/auth?...">Authorize Google Access</a>'

  /oauth2/callback:
    get:
      summary: OAuth2 callback endpoint
      tags:
        - Google
      operationId: googleCallback
      description: |
        Handles the callback from Google OAuth2 after user authorization.
        Exchanges the authorization code for an access token and stores credentials.
      parameters:
        - name: code
          in: query
          required: true
          description: Authorization code returned by Google after user consent.
          schema:
            type: string
      responses:
        '200':
          description: Authorization success message
          content:
            text/plain:
              schema:
                type: string
                example: Authorization successful! You can now use Calendar and Gmail APIs.
  /V1/token:
    post:
      tags:
        - Tokens
      summary: Generate bearer token
      operationId: getToken
      requestBody:
        required: true
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/GetTokenReq'
      responses:
        '200':
          description: Token response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/TokenRsp'
  /V1/freeslots/{year}/{month}/{day}:
    get:
      tags:
        - Reservations
      summary: Get all application users
      operationId: getFreeSlots
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
        - name: month
          in: path
          required: true
          schema:
            type: integer
        - name: day
          in: path
          required: true
          schema:
            type: integer
        - name: long
          in: query
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: List of application users
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                default: [ ]
                items:
                  $ref: "#/components/schemas/FreeSlotRest"
  /V1/confirmation:
    get:
      tags:
        - Reservations
      summary: Get all application users
      operationId: confirmEmailOK
      parameters:
        - name: uuid
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of application users
          content:
            text/html:
              schema:
                type: string
  /V1/reservation:
    post:
      tags:
        - Reservations
      summary: Post reservation from public page
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json; charset=utf-8:
            schema:
              type: object
              $ref: '#/components/schemas/ReservationRest'
      responses:
        '201':
          description: create/update reservation
    patch:
      tags:
        - Reservations
      summary: Delete user by Id
      operationId: updateReservation
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json; charset=utf-8:
            schema:
              type: object
              $ref: '#/components/schemas/UpdateReservationRest'
      responses:
        '201':
          description: Single user deleted
    delete:
      tags:
        - Reservations
      summary: Delete user by Id
      operationId: deleteAppointment
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Single user deleted
  /V1/reservations/{year}/{month}/{day}/{filter}:
    get:
      tags:
        - Reservations
      summary: Get all application users
      operationId: getWeekAppointments
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
        - name: year
          in: path
          required: true
          schema:
            type: integer
        - name: month
          in: path
          required: true
          schema:
            type: integer
        - name: day
          in: path
          required: true
          schema:
            type: integer
        - name: filter
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of application users
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                default: [ ]
                items:
                  $ref: "#/components/schemas/ReservationRest"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only
  schemas:
    GetTokenReq:
      properties:
        username:
          type: string
          minLength: 5
          maxLength: 30
        password:
          type: string
          minLength: 5
          maxLength: 80
        refresh_token:
          type: string
    TokenRsp:
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        refresh_expires_in:
          type: integer
        refresh_token:
          type: string
        token_type:
          type: string
        id_token:
          type: string
        not-before-policy:
          type: integer
        session_state:
          type: string
        scope:
          type: string
    ReservationRest:
      required:
        - name
        - email
        - phone
        - date_time
        - registration
        - long
        - confirmed
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 5
          maxLength: 128
        date_time:
          type: string
          format: date-time
        email:
          type: string
          minLength: 5
          maxLength: 80
        phone:
          type: string
          minLength: 5
          maxLength: 80
        registration:
          type: string
          minLength: 5
          maxLength: 80
        event_id:
          type: string
          minLength: 5
          maxLength: 80
        long:
          type: boolean
        confirmed:
          type: boolean
        email_ok:
          type: boolean
    FreeSlotRest:
      required:
        - start
        - end
      properties:
        start:
          type: string
          format: time
        end:
          type: string
          format: time
    UpdateReservationRest:
      required:
        - sendMail
        - approved
      properties:
        sendMail:
          type: boolean
        approved:
          type: boolean
        id:
          type: string
        email:
          type: string
